In [2]:
import pandas as pd
from pylab import rcParams
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn import metrics 
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
import statsmodels.formula.api as sm
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,PowerTransformer,PolynomialFeatures
from sklearn.linear_model import LinearRegression
import operator
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR

# GDP回归模型 （美国）

In [3]:
df=pd.read_csv("/home/mw/input/GDP_data1379/final_data.csv")
df=df[df['LOCATION']=='USA']

In [4]:
x=[i for i in df['TIME']]
y=[i for i in df['Value'].cumsum()]
x_array=x
y_array=y
x_shape=np.array(df['TIME'][:-1]).reshape(-1, 1)
y_shape=np.array(df['Value'][:-1].cumsum()).reshape(-1, 1)
x=np.asarray(x)
y=np.asarray(y)
x = x[:, np.newaxis]
y = y[:, np.newaxis]
l=int(len(x)*.7)
x_train,x_test=x[:l],x[l:]
y_train,y_test=y[:l],y[l:]

# 线性回归模型

In [6]:
polynomial_features= PolynomialFeatures(degree=1)
x_poly = polynomial_features.fit_transform(x)
model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-USA')
plt.legend(['Predicted data','Actual data'])
plt.show()
polynomial_features= PolynomialFeatures(degree=1)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 17.458929128074395
R方= -0.8808594140868322


# 二阶多项式回归模型

In [9]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.plot(x, y)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-USA')
plt.legend(['Actual data','Predicted data'])
plt.show()
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE 5.0332103384557465
R方= 0.8436811716952959


In [10]:
model.predict(polynomial_features.fit_transform(np.asarray([[2020]])))

array([[228.75532]])

**2020年美国GDP预测值**

# 三阶多项式回归模型

In [12]:
polynomial_features= PolynomialFeatures(degree=3)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-USA')
plt.legend(['Predicted data','Actual data'])
plt.show()
polynomial_features= PolynomialFeatures(degree=3)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 4.663959277629773
R方= 0.8657758597766309


In [13]:
model.predict(polynomial_features.fit_transform(np.asarray([[2020]])))

array([[235.79812126]])

# *GDP回归模型（印度）*

In [50]:
df=pd.read_csv("/home/mw/input/GDP_data1379/final_data.csv")
df=df[df['LOCATION']=='IND']

x=[i for i in df['TIME']]
y=[i for i in df['Value'].cumsum()]
x_array=x
y_array=y
x_shape=np.array(df['TIME'][:-1]).reshape(-1, 1)
y_shape=np.array(df['Value'][:-1].cumsum()).reshape(-1, 1)
x=np.asarray(x)
y=np.asarray(y)
x = x[:, np.newaxis]
y = y[:, np.newaxis]
l=int(len(x)*.8)
x_train,x_test=x[:l],x[l:]
y_train,y_test=y[:l],y[l:]

# 线性回归模型

In [42]:
polynomial_features= PolynomialFeatures(degree=1)
x_poly = polynomial_features.fit_transform(x)
model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.plot(x, y)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-India')
plt.legend(['Actual data','Predicted data'])
plt.show()
model = linear_model.LinearRegression()
model.fit(x_train,y_train)
y_poly_pred=model.predict(x_test.reshape(-1, 1))
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 1.4690977523751132
R方= 0.976664075924686


In [43]:
model.predict(np.asarray([[2020]]))[0]

array([163.58355946])

**2020年印度GDP预测值**

# 二阶多项式回归模型

In [51]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-India')
plt.legend(['Predicted data','Actual data'])
plt.show()
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 6.424757047073464
R方= 0.5536895728711293


# 三阶多项式回归模型

In [52]:
polynomial_features= PolynomialFeatures(degree=3)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
plt.scatter(x, y, s=10)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-India')
plt.legend(['Predicted data','Actual data'])
plt.show()

<Figure size 432x288 with 1 Axes>

# *GDP回归模型（南非）*

In [53]:
df=pd.read_csv("/home/mw/input/GDP_data1379/final_data.csv")
df=df[df['LOCATION']=='ZAF']

x=[i for i in df['TIME']]
y=[i for i in df['Value'].cumsum()]
x_array=x
y_array=y
x_shape=np.array(df['TIME'][:-1]).reshape(-1, 1)
y_shape=np.array(df['Value'][:-1].cumsum()).reshape(-1, 1)
x=np.asarray(x)
y=np.asarray(y)
x = x[:, np.newaxis]
y = y[:, np.newaxis]

l=int(len(x)*.8)
x_train,x_test=x[:l],x[l:]
y_train,y_test=y[:l],y[l:]

# 二阶多项式回归模型

In [55]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-South Africa')
plt.legend(['Predicted data','Actual data'])
plt.show()
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 23.63223254512106
R方= -15.478912371281837


In [57]:
#对数据进行归一化处理，为SVR奠定基础
scaler=StandardScaler()
dataset={'x':np.asarray(x).reshape(1,len(x))[0],'y':np.asarray(y).reshape(1,len(y))[0]}
df_data=pd.DataFrame(dataset)
normalized = scaler.fit_transform(df_data)
inverse = scaler.inverse_transform(normalized)
tobescaled=[]
for i in range(len(x)):
    tobescaled.append([x[i][0],y[i][0]])
tobescaled=np.asarray(tobescaled)
scaled = scaler.fit_transform(tobescaled)
x_scaled=[]
for i in range(len(x)):
    x_scaled.append([scaled[i][0]])
y_scaled=[]
for i in range(len(y)):
    y_scaled.append(scaled[i][1])

# 支持向量回归（SVR）

In [60]:
regressor = SVR(kernel='rbf')
regressor.fit(x_scaled,y_scaled)
y_pred = regressor.predict(x_scaled)
plt.scatter(x_scaled, y_scaled, color = 'magenta')
plt.plot(x_scaled, regressor.predict(x_scaled), color = 'green')
plt.xlabel('year') 
plt.ylabel('GDP') 
plt.title('GDP Model-South Africa')
plt.legend(['Predicted data','Actual data'])
plt.show()
l=int(len(x)*.8)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]
y_svr_pred=regressor.predict(x_test)
rmse = np.sqrt(mean_squared_error(regressor.predict(x_test),y_test))
r2 = r2_score(y_test,regressor.predict(x_test))
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 0.06458733142590245
R方= 0.7446640595853911


In [61]:
sc_x=StandardScaler()
sc_x.fit_transform(x)
sc_y=StandardScaler()
sc_y.fit_transform(y)
y_pred = sc_y.inverse_transform ((regressor.predict (sc_x.transform(np.array([[2020]])))))
print(y_pred)

[166.95715873]


**2020南非GDP预测值**

# 人工神经网络

In [62]:
from keras import models, layers
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

Using TensorFlow backend.


In [63]:
scaler.fit(x_train)
t1=scaler.transform(x_train)
test_t1=scaler.transform(x_test)
model = models.Sequential()
t2=np.asarray(y_train).reshape(1,len(y_train))[0]

In [65]:
model.add(layers.Dense(8, activation='relu', input_shape=[np.array(x_train).shape[1]]))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(1))
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
history = model.fit(t1,t2, validation_split=0.2, epochs=1000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Train on 37 samples, validate on 10 samples
Epoch 1/1000
37/37 [==============================] - 0s 4ms/step - loss: 0.9009 - mean_absolute_error: 0.6750 - val_loss: 0.4706 - val_mean_absolute_error: 0.6374
Epoch 2/1000
37/37 [==============================] - 0s 63us/step - loss: 0.8267 - mean_absolute_error: 0.6433 - val_loss: 0.4697 - val_mean_absolute_error: 0.6371
Epoch 3/1000
37/37 [==============================] - 0s 61us/step - loss: 0.7779 - mean_absolute_error: 0.6215 - val_loss: 0.4656 - val_mean_absolute_error: 0.6343
Epoch 4/1000
37/37 [==============================] - 0s 63us/step - loss: 0.7253 - mean_absolute_error: 0.5969 - val_loss: 0.4725 - val_mean_absolute_error: 0.6398
Epoch 5/1000
37/37 [==============================] - 0s 60us/step - loss: 0.6850 - mean_absolute_error: 0.5783 - val_loss: 0.4723 - val_mean_absolute_error: 0.6399
Epoch 6/1000

In [67]:
model.evaluate(test_t1, np.array(y_test).reshape(1,len(y_test))[0])
pred_values=model.predict(test_t1)
pred_values.reshape(1,len(pred_values))[0]

12/12 [==============================] - 0s 45us/step


array([0.4523257 , 0.47461414, 0.49690259, 0.51784724, 0.5385759 ,
       0.5593046 , 0.5800333 , 0.60101813, 0.6225417 , 0.6440654 ,
       0.66558903, 0.68711257], dtype=float32)

In [68]:
plt.scatter(test_t1,pred_values)
plt.plot(test_t1,y_test,'r')

<Figure size 432x288 with 1 Axes>