In [2]:
import pandas as pd
from pylab import rcParams
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn import metrics 
import seaborn as sns
from sklearn.preprocessing import PolynomialFeatures
import statsmodels.formula.api as sm
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,PowerTransformer,PolynomialFeatures
from sklearn.linear_model import LinearRegression
import operator
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import RidgeCV
from sklearn.model_selection import RepeatedKFold
from numpy import arange

# *国际贸易额回归模型（澳大利亚）*

In [7]:
df=pd.read_csv("/home/mw/input/trade8521/trade.csv")
df=df[df['LOCATION']=='AUS']
df[['TIME','Value']]
plt.scatter(df['TIME'],df['Value'])
plt.title('Trade-Australia')
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')

Text(0, 0.5, 'Trade (Million USD)')

<Figure size 432x288 with 1 Axes>

In [8]:
x=[i for i in df['TIME']]
y=[i for i in df['Value']]
x_array=x
y_array=y
x=np.asarray(x)
y=np.asarray(y)
x = x[:, np.newaxis]
y = y[:, np.newaxis]
l=int(len(x)*.8)
x_train,x_test=x[:l],x[l:]
y_train,y_test=y[:l],y[l:]

In [9]:
y=list(y)
y.remove([191.9768])
y.remove([188.1291])
x=list(x)
x.remove([2016])
x.remove([2015])

In [10]:
plt.plot(x,y)
plt.title('Trade-Australia')
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')

Text(0, 0.5, 'Trade (Million USD)')

<Figure size 432x288 with 1 Axes>

# 四阶多项式回归模型

In [11]:
polynomial_features= PolynomialFeatures(degree=4)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.title('Trade-Australia')
plt.legend(['observed data','predicted data'])
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')
plt.show()
polynomial_features= PolynomialFeatures(degree=4)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 74.72957230879437
R方= -2.1615604284619803


In [12]:
scaler = StandardScaler()
dataset={'x':np.asarray(x).reshape(1,len(x))[0],'y':np.asarray(y).reshape(1,len(y))[0]}
df_data=pd.DataFrame(dataset)
normalized = scaler.fit_transform(df_data)
inverse = scaler.inverse_transform(normalized)
tobescaled=[]
for i in range(len(x)):
    tobescaled.append([x[i][0],y[i][0]])
tobescaled=np.asarray(tobescaled)
scaled = scaler.fit_transform(tobescaled)
x_scaled=[]
for i in range(len(x)):
        x_scaled.append([scaled[i][0]])
y_scaled=[]
for i in range(len(y)):
        y_scaled.append(scaled[i][1])
l=int(len(x)*.90)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]

# 支持向量回归(SVR)

In [13]:
regressor = SVR(kernel='rbf')
regressor.fit(x_scaled,y_scaled)
y_svr_pred=regressor.predict(x_test)
y_pred = regressor.predict(x_scaled)
plt.plot(x_scaled, y_scaled, color = 'magenta')
plt.plot(x_scaled, regressor.predict(x_scaled), color = 'green')
plt.title('Trade-Australia')
plt.legend(['Actual data','Predicted data'])
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')
plt.show()

<Figure size 432x288 with 1 Axes>

In [14]:
l=int(len(x)*.8)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]
y_svr_pred=regressor.predict(x_test)
rmse = np.sqrt(mean_squared_error(regressor.predict(x_train),y_train))
r2 = r2_score(y_train,regressor.predict(x_train))
print("RMSE=",rmse)
print("R方=",r2)

RMSE= 0.10898426614227047
R方= 0.8800036467364301


In [15]:
sc_x=StandardScaler()
sc_x.fit_transform(x)
sc_y=StandardScaler()
sc_y.fit_transform(y)
y_pred = sc_y.inverse_transform ((regressor.predict (sc_x.transform(np.array([[2020]])))))
y_pred

array([257.43332689])

**2020年澳大利亚国际贸易额预测值**

# *国际贸易额回归模型（印度）*

In [29]:
df=pd.read_csv("/home/mw/input/trade8521/trade.csv")
df=df[df['LOCATION']=='IND']
df[['TIME','Value']]
plt.scatter(df['TIME'],df['Value'])
plt.title('Trade-India')
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')
x=[i for i in df['TIME']]
y=[i for i in df['Value']]
x_array=x
y_array=y
x=np.asarray(x)
y=np.asarray(y)
x = x[:, np.newaxis]
y = y[:, np.newaxis]
l=int(len(x)*.8)
x_train,x_test=x[:l],x[l:]
y_train,y_test=y[:l],y[l:]

<Figure size 432x288 with 1 Axes>

In [30]:
y=list(y)
y.remove([268.0791])
y.remove([264.6742])
y.remove([298.2488])
x=list(x)
x.remove([2016])
x.remove([2015])
x.remove([2017])

# 二阶多项式回归模型

In [31]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x)
model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.title('Trade-India')
plt.legend(['Predicted data','Actual data'])
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')
plt.show()
polynomial_features= PolynomialFeatures(degree=5)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 242.83503683013774
R方= -88.05070905504196


In [32]:
dataset={'x':np.asarray(x).reshape(1,len(x))[0],'y':np.asarray(y).reshape(1,len(y))[0]}
df_data=pd.DataFrame(dataset)
normalized = scaler.fit_transform(df_data)
# inverse transform
inverse = scaler.inverse_transform(normalized)
tobescaled=[]
for i in range(len(x)):
    tobescaled.append([x[i][0],y[i][0]])
tobescaled=np.asarray(tobescaled)
scaler = StandardScaler()
scaled = scaler.fit_transform(tobescaled)
x_scaled=[]
for i in range(len(x)):
        x_scaled.append([scaled[i][0]])
y_scaled=[]
for i in range(len(y)):
        y_scaled.append(scaled[i][1])
x_scaled=x_scaled[:-2]
y_scaled=y_scaled[:-2]
l=int(len(x)*.8)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]

# 支持向量回归(SVR)

In [33]:
regressor = SVR(kernel='rbf')
regressor.fit(x_scaled,y_scaled)
y_pred = regressor.predict(x_scaled)
plt.plot(x_scaled, y_scaled, color = 'magenta')
plt.plot(x_scaled, regressor.predict(x_scaled), color = 'green')
plt.title('Trade-India')
plt.legend(['Actual data','Predicted data'])
plt.ylabel('Trade (Million USD)')
plt.xlabel('Year')
plt.show()

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


<Figure size 432x288 with 1 Axes>

In [34]:
l=int(len(x)*.8)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]
y_svr_pred=regressor.predict(x_test)
rmse = np.sqrt(mean_squared_error(regressor.predict(x_train),y_train))
r2 = r2_score(y_train,regressor.predict(x_train))
print("RMSE=",rmse)
print("R方=",r2)

RMSE= 0.11702814250789302
R方= 0.9527453727608702


In [35]:
sc_x=StandardScaler()
sc_x.fit_transform(x)
sc_y=StandardScaler()
sc_y.fit_transform(y)
y_pred = sc_y.inverse_transform ((regressor.predict (sc_x.transform(np.array([[2020]])))))

In [36]:
y_pred

array([241.95275673])

**2020年印度国际贸易额预测值**

# *国际贸易额回归模型（南非）*

In [29]:
df=pd.read_csv("/home/mw/input/trade8521/trade.csv")
df=df[df['LOCATION']=='ZAF']
plt.plot(df['TIME'],df['Value'])
plt.title('Trade-South Africa')
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')

Text(0, 0.5, 'Trade (Million USD)')

<Figure size 432x288 with 1 Axes>

In [30]:
x=[i for i in df['TIME']]
y=[i for i in df['Value']]
x_array=x
y_array=y
x=np.asarray(x)
y=np.asarray(y)
x = x[:, np.newaxis]
y = y[:, np.newaxis]
l=int(len(x)*.8)
x_train,x_test=x[:l],x[l:]
y_train,y_test=y[:l],y[l:]

# 二阶多项式回归模型

In [31]:
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x)

model = LinearRegression()
model.fit(x_poly, y)
y_poly_pred = model.predict(x_poly)
rmse = np.sqrt(mean_squared_error(y,y_poly_pred))
r2 = r2_score(y,y_poly_pred)
plt.scatter(x, y, s=10)
# sort the values of x before line plot
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(x,y_poly_pred), key=sort_axis)
x, y_poly_pred = zip(*sorted_zip)
plt.plot(x, y_poly_pred, color='m')
plt.legend(['Predicted line','Actual data'])
plt.title('Trade-South Africa')
plt.xlabel('Year') 
plt.ylabel('Trade (Million USD)')
plt.show()
polynomial_features= PolynomialFeatures(degree=2)
x_poly = polynomial_features.fit_transform(x_train)
model = LinearRegression()
model.fit(x_poly, y_train)
x_test_poly=polynomial_features.fit_transform(x_test)
y_poly_pred = model.predict(x_test_poly)
rmse = np.sqrt(mean_squared_error(y_poly_pred,y_test))
r2 = r2_score(y_test,y_poly_pred)
print("RMSE=",rmse)
print("R方=",r2)

<Figure size 432x288 with 1 Axes>

RMSE= 33.480658693994116
R方= -6.630949864906526


In [32]:
dataset={'x':np.asarray(x).reshape(1,len(x))[0],'y':np.asarray(y).reshape(1,len(y))[0]}
df_data=pd.DataFrame(dataset)
tobescaled=[]
for i in range(len(x)):
    tobescaled.append([x[i][0],y[i][0]])
tobescaled=np.asarray(tobescaled)
scaler = StandardScaler()
scaled = scaler.fit_transform(tobescaled)
x_scaled=[]
for i in range(len(x)):
        x_scaled.append([scaled[i][0]])
y_scaled=[]
for i in range(len(y)):
        y_scaled.append(scaled[i][1])

# 支持向量回归(SVR)

In [33]:
l=int(len(x)*.8)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]
regressor = SVR(kernel='rbf')
regressor.fit(x_scaled,y_scaled)
y_pred = regressor.predict(x_scaled)
plt.plot(x_scaled, y_scaled, color = 'magenta')
plt.plot(x_scaled, regressor.predict(x_scaled), color = 'green')
plt.title('Trade-South Africa')
plt.legend(['Actual data','Predicted data'])
plt.xlabel('Year')
plt.ylabel('Trade (Million USD)')
plt.show()

<Figure size 432x288 with 1 Axes>

In [34]:
l=int(len(x)*.8)
x_train,x_test=x_scaled[:l],x_scaled[l:]
y_train,y_test=y_scaled[:l],y_scaled[l:]
y_svr_pred=regressor.predict(x_train)
rmse = np.sqrt(mean_squared_error(regressor.predict(x_train),y_train))
r2 = r2_score(y_train,regressor.predict(x_train))
print("RMSE=",rmse)
print("R方=",r2)

RMSE= 0.11650125521216997
R方= 0.9308005580144181


In [35]:
y_svr_pred=regressor.predict(x_test)
sc_x=StandardScaler()
sc_x.fit_transform(x)
sc_y=StandardScaler()
sc_y.fit_transform(y)
y_pred = sc_y.inverse_transform ((regressor.predict (sc_x.transform(np.array([[2020]])))))

In [36]:
y_pred

array([89.9684205])

**2020年南非国际贸易额预测值**